[2025-04-19T15:07:08.640+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:07:08.703+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:07:08.716+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:07:08.718+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:07:08.734+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:07:08.743+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmpvbe1v8hx']
[2025-04-19T15:07:08.745+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask load_new_orders
[2025-04-19T15:07:08.745+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=626) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:07:08.746+0000] {standard_task_runner.py:72} INFO - Started process 627 to run task
[2025-04-19T15:07:08.944+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:07:09.189+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:07:09.190+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:07:09.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-19T15:07:09.351+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:07:09.353+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T150708, end_date=20250419T150709
[2025-04-19T15:07:09.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T15:07:09.607+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:07:09.611+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T15:47:14.703+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:47:14.867+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:47:14.877+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:47:14.878+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:47:14.893+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:47:14.901+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4555) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:47:14.902+0000] {standard_task_runner.py:72} INFO - Started process 4556 to run task
[2025-04-19T15:47:14.902+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmpaqdr68xy']
[2025-04-19T15:47:14.904+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask load_new_orders
[2025-04-19T15:47:15.077+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:47:15.303+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:47:15.304+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:47:15.369+0000] {logging_mixin.py:190} INFO - Error loading orders: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^
[2025-04-19T15:47:15.370+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_to_sql_orders.py", line 46, in load_new_orders
    cursor.execute("""
psycopg2.errors.InvalidSchemaName: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^

[2025-04-19T15:47:15.430+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T154714, end_date=20250419T154715
[2025-04-19T15:47:15.568+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:47:15.569+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 231 for task load_new_orders (schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^
; 4556)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_to_sql_orders.py", line 46, in load_new_orders
    cursor.execute("""
psycopg2.errors.InvalidSchemaName: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^

[2025-04-19T15:47:15.599+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-19T15:47:15.670+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:47:15.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T15:47:52.008+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:47:52.075+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:47:52.090+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:47:52.091+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:47:52.108+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:47:52.115+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4645) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:47:52.116+0000] {standard_task_runner.py:72} INFO - Started process 4646 to run task
[2025-04-19T15:47:52.115+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmphjz0atpd']
[2025-04-19T15:47:52.117+0000] {standard_task_runner.py:105} INFO - Job 234: Subtask load_new_orders
[2025-04-19T15:47:52.315+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:47:52.538+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:47:52.539+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:47:52.608+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-19T15:47:52.659+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:47:52.660+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T154752, end_date=20250419T154752
[2025-04-19T15:47:52.814+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T15:47:52.881+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:47:52.884+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T15:48:21.278+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:48:21.349+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:48:21.365+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:48:21.365+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:48:21.382+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:48:21.389+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4711) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:48:21.389+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmp1bc4hal0']
[2025-04-19T15:48:21.390+0000] {standard_task_runner.py:72} INFO - Started process 4712 to run task
[2025-04-19T15:48:21.391+0000] {standard_task_runner.py:105} INFO - Job 237: Subtask load_new_orders
[2025-04-19T15:48:21.577+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:48:21.919+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:48:21.921+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:48:21.990+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-19T15:48:22.047+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:48:22.048+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T154821, end_date=20250419T154822
[2025-04-19T15:48:22.169+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T15:48:22.236+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:48:22.238+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T15:57:22.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:57:22.803+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:57:22.815+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:57:22.815+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:57:22.836+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:57:22.842+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5547) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:57:22.844+0000] {standard_task_runner.py:72} INFO - Started process 5548 to run task
[2025-04-19T15:57:22.843+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmpv9hww6at']
[2025-04-19T15:57:22.846+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask load_new_orders
[2025-04-19T15:57:23.119+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:57:23.357+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:57:23.361+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:57:23.437+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-19T15:57:23.490+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:57:23.491+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T155722, end_date=20250419T155723
[2025-04-19T15:57:23.663+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-19T15:57:23.738+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:57:23.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-19T15:58:25.946+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T15:58:25.999+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:58:26.009+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [queued]>
[2025-04-19T15:58:26.009+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-19T15:58:26.023+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-19 14:00:00+00:00
[2025-04-19T15:58:26.029+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5663) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T15:58:26.030+0000] {standard_task_runner.py:72} INFO - Started process 5664 to run task
[2025-04-19T15:58:26.030+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'scheduled__2025-04-19T14:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmpa909y1ec']
[2025-04-19T15:58:26.032+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask load_new_orders
[2025-04-19T15:58:26.191+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders scheduled__2025-04-19T14:00:00+00:00 [running]> on host 27536697ee14
[2025-04-19T15:58:26.534+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-19T14:00:00+00:00'
[2025-04-19T15:58:26.537+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T15:58:26.617+0000] {logging_mixin.py:190} INFO - Error loading orders: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^
[2025-04-19T15:58:26.618+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_to_sql_orders.py", line 46, in load_new_orders
    cursor.execute("""
psycopg2.errors.InvalidSchemaName: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^

[2025-04-19T15:58:26.681+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=load_new_orders, task_id=load_new_orders, run_id=scheduled__2025-04-19T14:00:00+00:00, execution_date=20250419T140000, start_date=20250419T155826, end_date=20250419T155826
[2025-04-19T15:58:26.910+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T15:58:26.911+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 252 for task load_new_orders (schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^
; 5664)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_to_sql_orders.py", line 46, in load_new_orders
    cursor.execute("""
psycopg2.errors.InvalidSchemaName: schema "commerce_raw" does not exist
LINE 2:         CREATE TEMP TABLE temp_new_orders (LIKE commerce_raw...
                                                        ^

[2025-04-19T15:58:26.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-19T15:58:27.001+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T15:58:27.008+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
