[2025-04-18T11:22:39.651+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T11:22:39.715+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders manual__2025-04-18T11:13:03.037399+00:00 [queued]>
[2025-04-18T11:22:39.728+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_orders.load_new_orders manual__2025-04-18T11:13:03.037399+00:00 [queued]>
[2025-04-18T11:22:39.729+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-04-18T11:22:39.746+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_orders> on 2025-04-18 11:13:03.037399+00:00
[2025-04-18T11:22:39.757+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T11:22:39.756+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_orders', 'load_new_orders', 'manual__2025-04-18T11:13:03.037399+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_orders.py', '--cfg-path', '/tmp/tmp_9p3s9x8']
[2025-04-18T11:22:39.758+0000] {standard_task_runner.py:72} INFO - Started process 308 to run task
[2025-04-18T11:22:39.758+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask load_new_orders
[2025-04-18T11:22:39.945+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_orders.load_new_orders manual__2025-04-18T11:13:03.037399+00:00 [running]> on host 9c8f13362ff5
[2025-04-18T11:22:40.196+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_orders' AIRFLOW_CTX_TASK_ID='load_new_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T11:13:03.037399+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T11:13:03.037399+00:00'
[2025-04-18T11:22:40.197+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T11:22:40.363+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T11:22:40.447+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T11:22:40.448+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_orders, task_id=load_new_orders, run_id=manual__2025-04-18T11:13:03.037399+00:00, execution_date=20250418T111303, start_date=20250418T112239, end_date=20250418T112240
[2025-04-18T11:22:40.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T11:22:40.924+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T11:22:40.932+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
