[2025-04-18T00:28:09.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T00:28:09.435+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items scheduled__2025-04-17T00:00:00+00:00 [queued]>
[2025-04-18T00:28:09.451+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_new_order_items.load_new_order_items scheduled__2025-04-17T00:00:00+00:00 [queued]>
[2025-04-18T00:28:09.454+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T00:28:09.480+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_new_order_items> on 2025-04-17 00:00:00+00:00
[2025-04-18T00:28:09.493+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T00:28:09.491+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_new_order_items', 'load_new_order_items', 'scheduled__2025-04-17T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/store_to_sql_order_items.py', '--cfg-path', '/tmp/tmpci8i542a']
[2025-04-18T00:28:09.494+0000] {standard_task_runner.py:72} INFO - Started process 308 to run task
[2025-04-18T00:28:09.495+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask load_new_order_items
[2025-04-18T00:28:09.743+0000] {task_command.py:467} INFO - Running <TaskInstance: load_new_order_items.load_new_order_items scheduled__2025-04-17T00:00:00+00:00 [running]> on host f693ba064550
[2025-04-18T00:28:10.089+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='load_new_order_items' AIRFLOW_CTX_TASK_ID='load_new_order_items' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T00:00:00+00:00'
[2025-04-18T00:28:10.091+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T00:28:10.441+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T00:28:10.501+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T00:28:10.502+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_new_order_items, task_id=load_new_order_items, run_id=scheduled__2025-04-17T00:00:00+00:00, execution_date=20250417T000000, start_date=20250418T002809, end_date=20250418T002810
[2025-04-18T00:28:10.723+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T00:28:10.789+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T00:28:10.793+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
